question_data = [{"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                  "question": "Jingle Bells was originally meant for Thanksgiving", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Science: Mathematics",
                  "question": "A universal set, or a set that contains all sets, exists.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film",
                  "question": "George Lucas directed the entire original Star Wars trilogy.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Television",
                  "question": "In &quot;Star Trek: The Next Generation&quot;, Data is the only android in existence.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "hard", "category": "Entertainment: Video Games",
                  "question": "The names of Roxas&#039;s Keyblades in Kingdom Hearts are &quot;Oathkeeper&quot; and &quot;Oblivion&quot;.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "hard", "category": "Science &amp; Nature",
                  "question": "The chemical element Lithium is named after the country of Lithuania.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Science &amp; Nature",
                  "question": "The Neanderthals were a direct ancestor of modern humans.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Books",
                  "question": "Shub-Niggurath is a creature that was created by \tJ. R. R. Tolkien in his novel &quot;The Lord of The Rings&quot;.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
                  "question": "The very first recorded computer &quot;bug&quot; was a moth found inside a Harvard Mark II computer.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Geography",
                  "question": "The Sonoran Desert is located in eastern Africa.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                  "question": "In &quot;Space Station 13&quot;,  the station has a clown aboard it.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "hard", "category": "History",
                  "question": "The fourth funnel of the RMS Titanic was fake designed to make the ship look more powerful and symmetrical.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Japanese Anime &amp; Manga",
                  "question": "In Pok&eacute;mon, Ash&#039;s Pikachu refuses to go into a pokeball.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
                  "question": "Haggis is traditionally ate on Burns Night.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Board Games",
                  "question": "&quot;PAYDAY: The Heist&quot; is a sequel to the board game &quot;Payday&quot;.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                  "question": "Scotland voted to become an independent country during the referendum from September 2014.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Geography",
                  "question": "St. Louis is the capital of the US State Missouri.", "correct_answer": "False",
                  "incorrect_answers": ["True"]}, {"type": "boolean", "difficulty": "easy", "category": "Animals",
                                                   "question": "The freshwater amphibian, the Axolotl, can regrow it&#039;s limbs.",
                                                   "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Geography",
                  "question": "Toronto is the capital city of the North American country of Canada.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
                  "question": "To bypass US Munitions Export Laws, the creator of the PGP published all the source code in book form. ",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
                  "question": "Tony Hawk&#039;s Pro Skater was released in 1999.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Film",
                  "question": "The movie &quot;Tron&quot; received an Oscar nomination for Best Visual Effects.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Mythology",
                  "question": "According to Norse mythology, Loki is a mother.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Science: Gadgets",
                  "question": "The communication protocol NFC stands for Near-Field Control.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                  "question": "Dihydrogen Monoxide is a dangerous chemical.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Board Games",
                  "question": "There is a Donald Trump Board Game, which was made in 1989.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Japanese Anime &amp; Manga",
                  "question": "In the &quot;Melancholy of Haruhi Suzumiya&quot; series, the narrator goes by the nickname Kyon.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
                  "question": "In &quot;Starbound&quot;, the track played by the Decorated Music Box is named &quot;Atlas&quot;.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "hard", "category": "History",
                  "question": "Japan was part of the Allied Powers during World War I.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
                  "question": "&quot;Santa Claus&quot; is a variety of melon.", "correct_answer": "True",
                  "incorrect_answers": ["False"]}]